### ISSUE TITLE
ImportError: libjasper.so.1: cannot open shared object file: No such file or directory on RPi

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/mqtt-camera-streamer#20]
Getting error on RPi: `ImportError: libjasper.so.1: cannot open shared object file: No such file or directory
`. Try: 
```
sudo apt-get install libatlas-base-dev
sudo apt-get install libjasper-dev
sudo apt-get install libqtgui4
sudo apt-get install python3-pyqt5
sudo apt-get install libqt4-test
```

Still getting the error. Run `sudo apt update --fix-missing` and restart pi. STILL getting this error, clearly a cv2 issue

**Comment by robmarkcole** [comment]
From [here](https://blog.piwheels.org/new-opencv-builds-including-opencv-4-x/) try:
```
sudo apt install libatlas3-base libwebp6 libtiff5 libjasper1 libilmbase23 libopenexr23 libavcodec58 libavformat58 libavutil56 libswscale5 libgtk-3-0 libpangocairo-1.0-0 libpango-1.0-0 libatk1.0-0 libcairo-gobject2 libcairo2 libgdk-pixbuf2.0-0 libqtgui4 libqt4-test libqtcore4
sudo pip3 install opencv-python
```
Hmm that just aborted

**Comment by OleWissing** [comment]
Tried the above on a fully updated Raspbian Buster on a RPi4 and got the following:

Traceback (most recent call last):
  File "scripts/camera.py", line 8, in <module>
    from imutils import opencv2matplotlib
  File "/home/pi/.local/lib/python3.7/site-packages/imutils/__init__.py", line 8, in <module>
    from .convenience import translate
  File "/home/pi/.local/lib/python3.7/site-packages/imutils/convenience.py", line 6, in <module>
    import cv2
  File "/home/pi/.local/lib/python3.7/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: /home/pi/.local/lib/python3.7/site-packages/cv2/cv2.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: __atomic_fetch_add_8

Any ideas?

**Comment by robmarkcole** [comment]
Ah opencv being a pain to install... I am going to write a seperate script for rpi using the picamera module, so opencv will not be a dependency on the rpi

**Comment by OleWissing** [comment]
You are a Saint! Thank You so much 🙏🏻

For your info. I got a little further by using this:

LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1.2.0 python3 

But then it fails with this message:

Traceback (most recent call last):
  File "scripts/camera.py", line 48, in <module>
    main()
  File "scripts/camera.py", line 37, in main
    np_array_RGB = opencv2matplotlib(frame)  # Convert to RGB
  File "/usr/local/lib/python3.7/dist-packages/imutils/convenience.py", line 130, in opencv2matplotlib
    return cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.1.1) /home/pi/opencv-python/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

I also tried earlier versions of cv2, with no luck.

You will fix a huge thing for us, who are using very small rtsp cameras (ESP32-CAM), that does not have the power or memory to handle an mqtt upload by themselves.

Keep up the good work You are doing.

/Ole

**Comment by robmarkcole** [comment]
Hi @OleWissing Ole
I am interest to learn more about your use case with the esp cam, can you share a link?
thanks

**Comment by OleWissing** [comment]
Here is some information:

ESP32-CAM:
https://a.aliexpress.com/_dUPOHhP

Micro-RTSP:
https://github.com/geeksville/Micro-RTSP

Another project:
https://randomnerdtutorials.com/esp32-cam-video-streaming-face-recognition-arduino-ide/

Med venlig hilsen / Best Regards / Saluda Atentamente

Ole Wissing

**Comment by robmarkcole** [comment]
Ok I updated the readme on how you can use the picamera with the official web_server example. I did spend a couple of hours trying alternaitve approaches but encountered issues. 
Cheers

**Comment by OleWissing** [comment]
It worked on a RPi4 using LD_PRELOAD of libatomic.so.1.2.0. 
It has now been running smoothly for the last 4-5 hours.
Thanks for your help.
